dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0
  - smartcontractkit/chainlink-brownie-contracts@0.5.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'
dotenv: .env